var drunk = {
    "beer":[
        {
            "nr": "141201",
            "artikelid": "939",
            "varunummer": "1412",
            "namn": "Norrlands Guld",
            "namn2": "Export",
            "prisinklmoms": "12.90",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "1955-10-01",
            "slutlev": " ",
            "varugrupp": "Ljus lager",
            "forpackning": "Flaska",
            "forslutning": "",
            "ursprung": "Dalarnas l\u00c3\u00a4n, Ludvika kommun",
            "ursprunglandnamn": "Sverige",
            "producent": "Spendrups",
            "leverantor": "Spendrups Bryggeri AB",
            "argang": "",
            "provadargang": "",
            "alkoholhalt": "5.3%",
            "modul": "",
            "sortiment": "FS",
            "ekologisk": "0",
            "koscher": "0",
            "img": ""
        }, {
            "nr": "167903",
            "artikelid": "1206",
            "varnummer": "1679",
            "namn": "Staropramen",
            "namn2": "",
            "prisinklmoms": "16.40",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "1994-02-14",
            "slutlev": " ",
            "varugrupp": "Ljus lager",
            "forpackning": "Flaska",
            "forslutning": "",
            "ursprung": "",
            "ursprunglandnamn": "Tjeckien",
            "producent": "Staropramen",
            "leverantor": "Carlsberg Sverige AB",
            "argang": "",
            "provadargang": "",
            "alkoholhalt": "5%",
            "modul": "",
            "sortiment": "FS",
            "ekologisk": "0",
            "koscher": "0",
            "img": ""
        }, {
            "nr": "167912",
            "artikelid": "507861",
            "varnummer": "1679",
            "namn": "Staropramen",
            "namn2": "",
            "prisinklmoms": "17.50",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "2011-11-18",
            "slutlev": " ",
            "varugrupp": "Ljus lager",
            "forpackning": "Burk",
            "forslutning": "",
            "ursprung": "",
            "ursprunglandnamn": "Tjeckien",
            "producent": "Staropramen",
            "leverantor": "Carlsberg Sverige AB",
            "argang": "",
            "provadargang": "",
            "alkoholhalt": "5%",
            "modul": "",
            "sortiment": "FS",
            "ekologisk": "0",
            "koscher": "0",
            "img": ""
        }, {
            "nr": "7101312",
            "artikelid": "522586",
            "varnummer": "71013",
            "namn": "Guinness",
            "namn2": "Draught Surger",
            "prisinklmoms": "23.50",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "2011-03-01",
            "slutlev": " ",
            "varugrupp": "Porter och Stout",
            "forpackning": "Burk",
            "forslutning": "",
            "ursprung": "",
            "ursprunglandnamn": "Irland",
            "producent": "Guinness",
            "leverantor": "Carlsberg Sverige AB",
            "argang": "",
            "provadargang": "",
            "alkoholhalt": "4.1%",
            "modul": "",
            "sortiment": "BS",
            "ekologisk": "0",
            "koscher": "0",
            "img": ""
        }, {
            "nr": "169912",
            "artikelid": "508200",
            "varnummer": "1699",
            "namn": "Svensk Stark\u00F6l",
            "namn2": "",
            "prisinklmoms": "8.60",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "2011-10-20",
            "slutlev": " ",
            "varugrupp": "Ljus lager",
            "forpackning": "Burk",
            "forslutning": "",
            "ursprung": "Kalmar l\u00E4n, Vimmerby kommun",
            "ursprunglandnamn": "Sverige",
            "producent": "\u00c3\u2026bro Bryggeri",
            "leverantor": "\u00c3\u2026bro Bryggeri",
            "argang": "",
            "provadargang": "",
            "alkoholhalt": "5.1%",
            "modul": "",
            "sortiment": "FS",
            "ekologisk": "0",
            "koscher": "0",
            "img": ""
        }, {
            "nr": "1104515",
            "artikelid": "721717",
            "varnummer": "11045",
            "namn": "Ten Fidy",
            "namn2": "Imperial Stout",
            "prisinklmoms": "49.80",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "2013-03-01",
            "slutlev": " ",
            "varugrupp": "Porter och Stout",
            "forpackning": "Burk",
            "forslutning": "",
            "ursprung": "",
            "ursprunglandnamn": "USA",
            "producent": "Oskar Blues Brewery",
            "leverantor": "Great Brands AB",
            "argang": "",
            "provadargang": "",
            "alkoholhalt": "10%",
            "modul": "",
            "sortiment": "TSE",
            "ekologisk": "0",
            "koscher": "0",
            "img": ""
        }, {
            "nr": "153603",
            "artikelid": "1132",
            "varnummer": "1536",
            "namn": "Heineken",
            "namn2": "",
            "prisinklmoms": "13.90",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "1992-04-21",
            "slutlev": " ",
            "varugrupp": "Ljus lager",
            "forpackning": "Flaska",
            "forslutning": "",
            "ursprung": "",
            "ursprunglandnamn": "Internationellt m\u00E4rke",
            "producent": "Spendrups",
            "leverantor": "Spendrups Bryggeri AB",
            "argang": "",
            "provadargang": "",
            "alkoholhalt": "5%",
            "modul": "",
            "sortiment": "FS",
            "ekologisk": "0",
            "koscher": "0",
            "img": ""
        }, {
            "nr": "102312",
            "artikelid": "1337",
            "varnummer": "",
            "namn": "Olvi",
            "namn2": "Tuplapukki",
            "prisinklmoms": "8.90",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "1990-04-21",
            "slutlev": " ",
            "varugrupp": "Djup lager",
            "forpackning": "Burk",
            "forslutning": "",
            "ursprung": "",
            "ursprunglandnamn": "Finland",
            "producent": "Olvi plc",
            "leverantor": "Olvi plc",
            "argang": "",
            "provadargang": "",
            "alkoholhalt": "8.5%",
            "modul": "",
            "sortiment": "FS",
            "ekologisk": "0",
            "koscher": "0",
            "img": ""
        }
    ],
    "spirits" : {
        "whiskey": [
            {
            "nr": "1024601",
            "artikelid": "560847",
            "varnummer": "10246",
            "namn": "The Whisky Agency",
            "namn2": "Laphroaig",
            "prisinklmoms": "725.00",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "2011-03-15",
            "slutlev": " ",
            "varugrupp": "Malt",
            "forpackning": "Flaska",
            "forslutning": "",
            "ursprung": "Skottland, Islay",
            "ursprunglandnamn": "Storbritannien",
            "producent": "The Whisky Agency",
            "leverantor": "Origo Wine Import",
            "argang": "2000",
            "provadargang": "",
            "alkoholhalt": "52.5%",
            "modul": "T7",
            "sortiment": "TSE",
            "ekologisk": "0",
            "koscher": "0",
            "img": ""
            },
            {
            "nr": "8551301",
            "artikelid": "850724",
            "varnummer": "85513",
            "namn": "Paul John",
            "namn2": "Classic Select Cask",
            "prisinklmoms": "890.00",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "2014-05-02",
            "slutlev": " ",
            "varugrupp": "Malt",
            "forpackning": "Flaska",
            "forslutning": "",
            "ursprung": "",
            "ursprunglandnamn": "Indien",
            "producent": "John Distilleries",
            "leverantor": "Whiskytaste Sweden AB",
            "argang": "",
            "provadargang": "",
            "alkoholhalt": "55.2%",
            "modul": "",
            "sortiment": "BS",
            "ekologisk": "0",
            "koscher": "0",
            "img": ""
            }
        ],
        "cognac" : [
            {
            "nr": "7019401",
            "artikelid": "37672",
            "varnummer": "70194",
            "namn": "L'H\u00E9raud",
            "namn2": "VSOP",
            "prisinklmoms": "399.00",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "2002-11-01",
            "slutlev": " ",
            "varugrupp": "Cognac",
            "forpackning": "Flaska",
            "forslutning": "",
            "ursprung": "Cognac",
            "ursprunglandnamn": "Frankrike",
            "producent": "Cognac L'H\u00E9raud",
            "leverantor": "Amka Vinimport AB",
            "argang": "",
            "provadargang": "",
            "alkoholhalt": "40%",
            "modul": "",
            "sortiment": "BS",
            "ekologisk": "0",
            "koscher": "0",
            "img": ""
            },
            {
            "nr": "8664601",
            "artikelid": "320747",
            "varnummer": "86646",
            "namn": "Delamain",
            "namn2": "Vesper",
            "prisinklmoms": "1129.00",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "2008-05-02",
            "slutlev": " ",
            "varugrupp": "Cognac",
            "forpackning": "Flaska",
            "forslutning": "",
            "ursprung": "Cognac, Grande Champagne",
            "ursprunglandnamn": "Frankrike",
            "producent": "Delamain",
            "leverantor": "Johan Lidby Vinhandel AB",
            "argang": "",
            "provadargang": "",
            "alkoholhalt": "40%",
            "modul": "",
            "sortiment": "BS",
            "ekologisk": "0",
            "koscher": "0",
            "img": ""
            },
            {
            "nr": "17102",
            "artikelid": "225",
            "varnummer": "171",
            "namn": "Martell VS***",
            "namn2": "",
            "prisinklmoms": "195.00",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "1992-08-28",
            "slutlev": " ",
            "varugrupp": "Cognac",
            "forpackning": "Flaska",
            "forslutning": "",
            "ursprung": "Cognac",
            "ursprunglandnamn": "Frankrike",
            "producent": "Martell",
            "leverantor": "Pernod Ricard Sweden AB",
            "argang": "",
            "provadargang": "",
            "alkoholhalt": "40%",
            "modul": "",
            "sortiment": "FS",
            "ekologisk": "0",
            "koscher": "0",
            "img": ""
        }
        ],
        "rum" : [
            {
            "nr": "59101",
            "artikelid": "47035",
            "varnummer": "591",
            "namn": "Captain Morgan",
            "namn2": "Jamaica Rum",
            "prisinklmoms": "240.00",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "2004-03-01",
            "slutlev": " ",
            "varugrupp": "M\u00F6rk",
            "forpackning": "Flaska",
            "forslutning": "",
            "ursprung": "",
            "ursprunglandnamn": "Jamaica",
            "producent": "Captain Morgan",
            "leverantor": "Diageo Sweden AB",
            "argang": "",
            "provadargang": "",
            "alkoholhalt": "40%",
            "modul": "",
            "sortiment": "FS",
            "ekologisk": "0",
            "koscher": "0",
            "img": ""
            },
            {
            "nr": "7017701",
            "artikelid": "32224",
            "varnummer": "70177",
            "namn": "Cacha\u00E97a 51",
            "namn2": "",
            "prisinklmoms": "249.00",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "2001-12-01",
            "slutlev": " ",
            "varugrupp": "Ljus",
            "forpackning": "Flaska",
            "forslutning": "Skruvkapsyl",
            "ursprung": "",
            "ursprunglandnamn": "Brasilien",
            "producent": "M\u00FCller de Bebidas",
            "leverantor": "TOMP Beer Wine & Spirits AB",
            "argang": "",
            "provadargang": "",
            "alkoholhalt": "40%",
            "modul": "",
            "sortiment": "FS",
            "ekologisk": "0",
            "koscher": "0",
            "img": ""
            }, 
            {
            "nr": "8628801",
            "artikelid": "701664",
            "varnummer": "86288",
            "namn": "Flying Dutchman Rum",
            "namn2": "",
            "prisinklmoms": "485.00",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "2012-10-01",
            "slutlev": " ",
            "varugrupp": "Ljus",
            "forpackning": "Flaska",
            "forslutning": "",
            "ursprung": "",
            "ursprunglandnamn": "Nederl\u00E4nderna",
            "producent": "Zuidam Distillers BV",
            "leverantor": "Clydesdale AB",
            "argang": "",
            "provadargang": "",
            "alkoholhalt": "40%",
            "modul": "",
            "sortiment": "BS",
            "ekologisk": "0",
            "koscher": "0",
            "img": ""
            }

        ]
    },
    "wine" : [
        {
            "nr": "9605501",
            "artikelid": "668007",
            "varnummer": "96055",
            "namn": "Ch\u00E92teau Cambon la Pelouse",
            "namn2": "",
            "prisinklmoms": "191.00",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "2012-10-01",
            "slutlev": " ",
            "varugrupp": "R\u00F6tt vin, Stramt & Nyanserat",
            "forpackning": "Flaska",
            "forslutning": "Naturkork",
            "ursprung": "Bordeaux, Haut-M\u00E9doc",
            "ursprunglandnamn": "Frankrike",
            "producent": "",
            "leverantor": "Tryffelsvinet AB",
            "argang": "2009",
            "provadargang": "2009",
            "alkoholhalt": "14%",
            "modul": "T5",
            "sortiment": "TSE",
            "ekologisk": "0",
            "koscher": "0",
            "img": ""
        }, {
            "nr": "9635001",
            "artikelid": "686251",
            "varnummer": "96350",
            "namn": "Torbreck",
            "namn2": "Woodcutter's Shiraz",
            "prisinklmoms": "219.00",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "2012-11-01",
            "slutlev": " ",
            "varugrupp": "R\u00F6tt vin, Fruktigt & Smakrikt",
            "forpackning": "Flaska",
            "forslutning": "Skruvkapsyl",
            "ursprung": "South Australia, Barossa Valley",
            "ursprunglandnamn": "Australien",
            "producent": "Torbreck Vintners",
            "leverantor": "Divine AB",
            "argang": "2011",
            "provadargang": "2011",
            "alkoholhalt": "14.5%",
            "modul": "T6",
            "sortiment": "TSE",
            "ekologisk": "0",
            "koscher": "0",
            "img": ""
        }
    ],
    "alcoholfree": [
            {
            "nr": "190002",
            "artikelid": "417665",
            "varnummer": "1900",
            "namn": "St\u00F6rtebeker 1402",
            "namn2": "",
            "prisinklmoms": "11.90",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "2009-12-01",
            "slutlev": " ",
            "varugrupp": "\u00D6l",
            "forpackning": "Flaska",
            "forslutning": "",
            "ursprung": "",
            "ursprunglandnamn": "Tyskland",
            "producent": "Stralsunder Brauerei",
            "leverantor": "Heba Food & Beverages AB",
            "argang": "",
            "provadargang": "",
            "alkoholhalt": "0.2%",
            "modul": "",
            "sortiment": "FS\u00D6",
            "ekologisk": "1",
            "koscher": "0",
            "img": ""
            },
            {
            "nr": "198001",
            "artikelid": "603008",
            "varnummer": "1980",
            "namn": "Jus de Raisin",
            "namn2": "Rouge",
            "prisinklmoms": "49.00",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "2012-03-01",
            "slutlev": " ",
            "varugrupp": "Must",
            "forpackning": "Flaska",
            "forslutning": "Skruvkapsyl",
            "ursprung": "",
            "ursprunglandnamn": "Frankrike",
            "producent": "Les Vignobles Laurie & Guillau",
            "leverantor": "TM Kvalitetsviner AB",
            "argang": "2011",
            "provadargang": "",
            "alkoholhalt": "0%",
            "modul": "",
            "sortiment": "TSV",
            "ekologisk": "1",
            "koscher": "0",
            "img": ""
            },
            {
            "nr": "199601",
            "artikelid": "539772",
            "varnummer": "1996",
            "namn": "Toselli",
            "namn2": "Spumante",
            "prisinklmoms": "34.00",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "2011-04-01",
            "slutlev": " ",
            "varugrupp": "Mousserande",
            "forpackning": "Flaska",
            "forslutning": "Skruvkapsyl",
            "ursprung": "",
            "ursprunglandnamn": "Italien",
            "producent": "Bosca Spa",
            "leverantor": "Spendrups Bryggeri AB",
            "argang": "",
            "provadargang": "",
            "alkoholhalt": "0.3%",
            "modul": "",
            "sortiment": "FS\u00D6",
            "ekologisk": "0",
            "koscher": "0",
            "img": ""
            },
            {
            "nr": "9040301",
            "artikelid": "579221",
            "varnummer": "90403",
            "namn": "Maglehem n:o 4",
            "namn2": "",
            "prisinklmoms": "48.00",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "2011-09-01",
            "slutlev": " ",
            "varugrupp": "Must",
            "forpackning": "Flaska",
            "forslutning": "",
            "ursprung": "Sk\u00E95ne l\u00E4n, Kristianstads kommun",
            "ursprunglandnamn": "Sverige",
            "producent": "Maglehems musteri",
            "leverantor": "Maglehems Musteri AB",
            "argang": "",
            "provadargang": "",
            "alkoholhalt": "0%",
            "modul": "",
            "sortiment": "TSV",
            "ekologisk": "1",
            "koscher": "0",
            "img": ""
        },
        {
            "nr": "195802",
            "artikelid": "788406",
            "varnummer": "1958",
            "namn": "Mikkeller",
            "namn2": "Drink'in The Snow",
            "prisinklmoms": "16.90",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "2013-11-15",
            "slutlev": " ",
            "varugrupp": "\u00D6l",
            "forpackning": "Flaska",
            "forslutning": "",
            "ursprung": "",
            "ursprunglandnamn": "Belgien",
            "producent": "De Proef Brouwerij",
            "leverantor": "Brill & Co AB",
            "argang": "",
            "provadargang": "",
            "alkoholhalt": "0.3%",
            "modul": "",
            "sortiment": "TSS",
            "ekologisk": "0",
            "koscher": "0",
            "img": ""
        },
        {
            "nr": "197901",
            "artikelid": "790110",
            "varnummer": "1979",
            "namn": "Richard Juhlin",
            "namn2": "Blanc de Blancs Non-Alcoholic Sparkling Wine",
            "prisinklmoms": "89.00",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "2013-12-02",
            "slutlev": " ",
            "varugrupp": "Mousserande",
            "forpackning": "Flaska",
            "forslutning": "Plastkork\/syntetkork",
            "ursprung": "",
            "ursprunglandnamn": "Frankrike",
            "producent": "MRG Wines",
            "leverantor": "Pernod Ricard Sweden AB",
            "argang": "",
            "provadargang": "",
            "alkoholhalt": "0%",
            "modul": "",
            "sortiment": "FS\u00D6",
            "ekologisk": "0",
            "koscher": "0",
            "img": ""
        },
        {
            "nr": "191402",
            "artikelid": "864046",
            "varnummer": "1914",
            "namn": "Einbecker Brauherren Alkoholfrei",
            "namn2": "",
            "prisinklmoms": "9.90",
            "volymiml": null,
            "prisperliter": null,
            "saljstart": "2014-09-01",
            "slutlev": " ",
            "varugrupp": "\u00D6l",
            "forpackning": "Flaska",
            "forslutning": "",
            "ursprung": "",
            "ursprunglandnamn": "Tyskland",
            "producent": "Einbecker Brauhaus",
            "leverantor": "AB Wicked Wine Sweden",
            "argang": "",
            "provadargang": "",
            "alkoholhalt": "0.5%",
            "modul": "",
            "sortiment": "FS\u00D6",
            "ekologisk": "0",
            "koscher": "0",
            "img": ""
        }
    ]
}
