/*
 *  Storage for all the products being sold in the bar 
 */
var drunk = {
    "beer":[
        {
            "articleid": "939",
            "name": "Norrlands Guld",
            "name2": "Export",
            "pricewithvat": "12.90",
            "volume": "330 ml",
            "productgroup": "Ljus lager",
            "serves": "Flaska",
            "origin": "Dalarnas l\u00c3\u00a4n, Ludvika kommun",
            "origincountry": "Sverige",
            "producent": "Spendrups",
            "alcoholcontent": "5.3%",
            "img": "./img/norrlands.png",
            "stock": 3
        }, {
            "articleid": "1206",    
            "name": "Staropramen",
            "name2": "",
            "pricewithvat": "16.40",
            "volume": "330 ml",
            "productgroup": "Ljus lager",
            "serves": "Flaska",
            "origin": "",
            "origincountry": "Tjeckien",
            "producent": "Staropramen",
            "alcoholcontent": "5%",
            "img": "./img/staropramen.png",
            "stock": 10
        }, {
            "articleid": "522586",
            "name": "Guinness",
            "name2": "Draught Surger",
            "pricewithvat": "23.50",
            "volume": "500 ml",
            "productgroup": "Porter och Stout",
            "serves": "Burk",
            "origin": "",
            "origincountry": "Irland",
            "producent": "Guinness",
            "alcoholcontent": "4.1%",
            "img": "./img/guinness.png",
            "stock": 10
        }, {
            "articleid": "508200",
            "name": "Svensk Stark\u00F6l",
            "name2": "",
            "pricewithvat": "8.60",
            "volume": "330 ml",
            "productgroup": "Ljus lager",
            "serves": "Burk",
            "origin": "Kalmar l\u00E4n, Vimmerby kommun",
            "origincountry": "Sverige",
            "producent": "\u00c3\u2026bro Bryggeri",
            "alcoholcontent": "5.1%",
            "img": "./img/svensk_stark.png",
            "stock": 10
        }, {
            "articleid": "721717",
            "name": "Ten Fidy",
            "name2": "Imperial Stout",
            "pricewithvat": "49.80",
            "volume": "330 ml",
            "productgroup": "Porter och Stout",
            "serves": "Burk",
            "origin": "",
            "origincountry": "USA",
            "producent": "Oskar Blues Brewery",
            "alcoholcontent": "10%",
            "img": "./img/ten_fidy.png",
            "stock": 10
        }, {
            "articleid": "1132",
            "name": "Heineken",
            "name2": "",
            "pricewithvat": "13.90",
            "volume": "330 ml",
            "productgroup": "Ljus lager",
            "serves": "Flaska",
            "origin": "",
            "origincountry": "Internationellt m\u00E4rke",
            "producent": "Spendrups",
            "alcoholcontent": "5%",
            "img": "./img/heineken.png",
            "stock": 10
        }, {
            "articleid": "1337",
            "name": "Olvi",
            "name2": "Tuplapukki",
            "pricewithvat": "8.90",
            "volume": "330 ml",
            "productgroup": "Djup lager",
            "serves": "Burk",
            "origin": "",
            "origincountry": "Finland",
            "producent": "Olvi plc",
            "alcoholcontent": "8.5%",
            "img": "./img/olvi.jpeg",
            "stock": 10
        }
    ],
    "spirits" : [
        {
            "articleid": "560847",
            "name": "The Whisky Agency",
            "name2": "Laphroaig",
            "pricewithvat": "725.00",
            "volume": null,
            "productgroup": "Whiskey, Malt",
            "serves": "Flaska",
            "origin": "Skottland, Islay",
            "origincountry": "Storbritannien",
            "producent": "The Whisky Agency",
            "alcoholcontent": "52.5%",
            "img": "",
            "stock": 10
        }, {
            "articleid": "850724",
            "name": "Paul John",
            "name2": "Classic Select Cask",
            "pricewithvat": "890.00",
            "volume": null,
            "productgroup": "Whiskey, Malt",
            "serves": "Flaska",
            "origin": "",
            "origincountry": "Indien",
            "producent": "John Distilleries",
            "alcoholcontent": "55.2%",
            "img": "",
            "stock": 10
        },{
            "articleid": "37672",
            "name": "L'H\u00E9raud",
            "name2": "VSOP",
            "pricewithvat": "399.00",
            "volume": null,
            "productgroup": "Cognac",
            "serves": "Flaska",
            "origin": "Cognac",
            "origincountry": "Frankrike",
            "producent": "Cognac L'H\u00E9raud",
            "alcoholcontent": "40%",
            "img": "",
            "stock": 10
        },{
            "articleid": "320747",
            "name": "Delamain",
            "name2": "Vesper",
            "pricewithvat": "1129.00",
            "volume": null,
            "productgroup": "Cognac",
            "serves": "Flaska",
            "origin": "Cognac, Grande Champagne",
            "origincountry": "Frankrike",
            "producent": "Delamain",
            "alcoholcontent": "40%",
            "img": "",
            "stock": 10
        },{
            "articleid": "225",
            "name": "Martell VS***",
            "name2": "",
            "pricewithvat": "195.00",
            "volume": null,
            "productgroup": "Cognac",
            "serves": "Flaska",
            "origin": "Cognac",
            "origincountry": "Frankrike",
            "producent": "Martell",
            "alcoholcontent": "40%",
            "img": "",
            "stock": 10
        },{
            "articleid": "47035",
            "name": "Captain Morgan",
            "name2": "Jamaica Rum",
            "pricewithvat": "240.00",
            "volume": null,
            "productgroup": "Rom, M\u00F6rk",
            "serves": "Flaska",
            "origin": "",
            "origincountry": "Jamaica",
            "producent": "Captain Morgan",
            "alcoholcontent": "40%",
            "img": "",
            "stock": 10
        },{
            "articleid": "32224",
            "name": "Cacha\u00E97a 51",
            "name2": "",
            "pricewithvat": "249.00",
            "volume": null,
            "productgroup": "Rom, Ljus",
            "serves": "Flaska",
            "origin": "",
            "origincountry": "Brasilien",
            "producent": "M\u00FCller de Bebidas",
            "alcoholcontent": "40%",
            "img": "",
            "stock": 10
        }, {
            "articleid": "701664",
            "name": "Flying Dutchman Rum",
            "name2": "",
            "pricewithvat": "485.00",
            "volume": null,
            "productgroup": "Rom, Ljus",
            "serves": "Flaska",
            "origin": "",
            "origincountry": "Nederl\u00E4nderna",
            "producent": "Zuidam Distillers BV",
            "alcoholcontent": "40%",
            "img": "",
            "stock": 10
            }
        ],
    "wine" : [
        {
            "articleid": "668007",
            "name": "Ch\u00E9teau Cambon la Pelouse",
            "name2": "",
            "pricewithvat": "191.00",
            "volume": null,
            "productgroup": "R\u00F6tt vin, Stramt & Nyanserat",
            "serves": "Flaska",
            "origin": "Bordeaux, Haut-M\u00E9doc",
            "origincountry": "Frankrike",
            "producent": "Tryffelsvinet AB",
            "alcoholcontent": "14%",
            "img": "./img/chateau_la_pelouse.png",
            "stock": 10
        }, {
            "nr": "9635001",
            "articleid": "686251",
            "varnummer": "96350",
            "name": "Torbreck",
            "name2": "Woodcutter's Shiraz",
            "pricewithvat": "219.00",
            "volume": null,
            "productgroup": "R\u00F6tt vin, Fruktigt & Smakrikt",
            "serves": "Flaska",
            "origin": "South Australia, Barossa Valley",
            "origincountry": "Australien",
            "producent": "Torbreck Vintners",
            "alcoholcontent": "14.5%",
            "img": "./img/torbreck.png",
            "stock": 10
        }
    ],
    "non-alcoholic": [
        {
            "articleid": "417665",
            "name": "St\u00F6rtebeker 1402",
            "name2": "",
            "pricewithvat": "11.90",
            "volume": null,
            "productgroup": "\u00D6l",
            "serves": "Flaska",
            "origin": "",
            "origincountry": "Tyskland",
            "producent": "Stralsunder Brauerei",
            "alcoholcontent": "0.2%",
            "img": ""
        },{
            "articleid": "603008",
            "name": "Jus de Raisin",
            "name2": "Rouge",
            "pricewithvat": "49.00",
            "volume": null,
            "productgroup": "Must",
            "serves": "Flaska",
            "origin": "",
            "origincountry": "Frankrike",
            "producent": "Les Vignobles Laurie & Guillau",
            "alcoholcontent": "0%",
            "img": "",
            "stock": 10
        },{
            "articleid": "539772",
            "name": "Toselli",
            "name2": "Spumante",
            "pricewithvat": "34.00",
            "volume": null,
            "productgroup": "Mousserande",
            "serves": "Flaska",
            "origin": "",
            "origincountry": "Italien",
            "producent": "Bosca Spa",
            "alcoholcontent": "0.3%",
            "img": "",
            "stock": 10
        },{
            "articleid": "579221",
            "name": "Maglehem n:o 4",
            "name2": "",
            "pricewithvat": "48.00",
            "volume": null,
            "productgroup": "Must",
            "serves": "Flaska",
            "origin": "Sk\u00E95ne l\u00E4n, Kristianstads kommun",
            "origincountry": "Sverige",
            "producent": "Maglehems musteri",
            "alcoholcontent": "0%",
            "img": "",
            "stock": 10
        },{
            "articleid": "788406",
            "name": "Mikkeller",
            "name2": "Drink'in The Snow",
            "pricewithvat": "16.90",
            "volume": null,
            "productgroup": "\u00D6l",
            "serves": "Flaska",
            "origin": "",
            "origincountry": "Belgien",
            "producent": "De Proef Brouwerij",
            "alcoholcontent": "0.3%",
            "img": "",
            "stock": 10
        },{
            "articleid": "790110",
            "name": "Richard Juhlin ",
            "name2": "Blanc de Blancs Non-Alcoholic Sparkling Wine",
            "pricewithvat": "89.00",
            "volume": null,
            "productgroup": "Mousserande",
            "serves": "Flaska",
            "origin": "",
            "origincountry": "Frankrike",
            "producent": "MRG Wines",
            "alcoholcontent": "0%",
            "img": "",
            "stock": 10
        },{
            "articleid": "864046",
            "name": "Einbecker Brauherren Alkoholfrei",
            "name2": "",
            "pricewithvat": "9.90",
            "volume": null,
            "productgroup": "\u00D6l",
            "serves": "Flaska",
            "origin": "",
            "origincountry": "Tyskland",
            "producent": "Einbecker Brauhaus",
            "alcoholcontent": "0.5%",
            "img": "",
            "stock": 10
        },{
            "articleid": "10902",
            "name": "Pepsi",
            "name2": "",
            "pricewithvat": "5:90",
            "volume": "330 ml",
            "productgroup": "Läsk",
            "serves": "Flaska",
            "origin": "",
            "origincountry": "AMERICA",
            "producent": "The Coca-Cola Company",
            "alcoholcontent": "Inget",
            "img": "",
            "stock": 10
        }
    ],
    "secret": [
        {
            "articleid": "10392",
            "name": "Supa Olvi",
            "name2": "Tuplapukki",
            "pricewithvat": "10.90",
            "volume": "500 ml",
            "productgroup": "Öl",
            "serves": "Flaska",
            "origin": "Månen",
            "origincountry": "Vintergatan",
            "producent": "Aliens",
            "alcoholcontent": "69.420%",
            "img": "./img/olvi.jpeg",
            "stock": 69
        }

    ],
    "food": [
        {
            "articleid": "11234",
            "name": "Hamburgare med pommes",
            "name2": "Chef special",
            "pricewithvat": "59",
            "volume": "200g",
            "productgroup": "Hamburgare",
            "serves": "Tallrik",
            "origin": "Värmlands gård",
            "origincountry": "Sverige",
            "producent": "Arla",
            "alcoholcontent": "",
            "img": "./img/burgare.png",
            "stock": 69
        },{
            "articleid": "85555",
            "name": "Vesuvio",
            "name2": "Chef Special",
            "pricewithvat": "70",
            "volume": "500g",
            "productgroup": "Pizza",
            "serves": "Tallrik",
            "origin": "Italien",
            "origincountry": "Italien",
            "producent": "Dominos",
            "alcoholcontent": "Inget",
            "img": "./img/vesuvio.png",
            "stock": 10
        },{
            "articleid": "85666",
            "name": "Nachotallrik",
            "name2": "Chef Special",
            "pricewithvat": "30",
            "volume": "200",
            "productgroup": "Nachotallrik",
            "serves": "Tallrik",
            "origin": "Mexiko",
            "origincountry": "Mexiko",
            "producent": "ICA",
            "alcoholcontent": "Inget",
            "img": "./img/nachos.png",
            "stock": 10
        }

    ]
}
